# Generated by Django 3.1.3 on 2020-11-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='_balance',
            field=models.IntegerField(blank=True, db_column='balance', null=True),
        ),
    ]
