# Generated by Django 3.1.3 on 2020-11-06 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account__balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='_balance',
        ),
    ]
